name: myapp
channels:
- birdhouse
- defaults
- conda-forge
dependencies:
- python=2.7
- pyyaml=3.12
- cryptography=1.8
- pyopenssl=17.0
# buildout
- mako
# tests
- pytest=3.1
# pep8
- flake8=3.3
- pycodestyle=2.3
# wps
- pywps=4.0.0
- nginx=1.10.3
- supervisor=3.3
- gunicorn=19.7
- gevent=1.2
- lxml=3.7
- genshi=0.7
# postgres
- psycopg2
# plotter
- cartopy
- netcdf4
